version: 2.1
docker-publisher: &docker-publisher
    working_directory: ~/repo
    environment:
        IMAGE_NAME: hachikoapp/expresscart
    docker:
        - image: circleci/buildpack-deps:stretch

gcloud: &gcloud
    working_directory: ~/repo
    docker:
        - image: google/cloud-sdk:275.0.0
    environment:
        GOOGLE_APPLICATION_CREDENTIALS: ~/repo/kubernetes-2020-3e7c463a81eb.json

jobs:
    build:
        <<: *docker-publisher
        steps:
            - checkout
            - run:
                name: gcp auth
                command: echo $GCP_CREDENTIALS > kubernetes-2020-3e7c463a81eb.json
            - setup_remote_docker
            - run:
                name: Build Docker Image
                command: |
                    docker build -t $IMAGE_NAME:latest .
            - run:
                name: Archive Docker Image
                command: docker save -o image.tar $IMAGE_NAME
            - persist_to_workspace:
                root: ~/repo
                paths: .
    publish-latest:
        <<: *docker-publisher
        steps:
            - attach_workspace:
                at: ~/repo
            - setup_remote_docker
            - run:
                name: Load archived Docker Image
                command: docker load -i image.tar
            - run:
                name: Publish Docker Image to Docker Hub
                command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker push "$IMAGE_NAME:latest"
    expresscart-deployment:
        <<: *gcloud
        steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: authentication
                command: gcloud auth activate-service-account --key-file ${HOME}/repo/kubernetes-2020-3e7c463a81eb.json || die "unable to authenticate service account for gcloud"
            - run:
                name: set_zone
                command: gcloud --quiet config set compute/zone us-central1-a
            - run:
                name: expresscart-deploy
                command: ./deploy_expresscart.sh
workflows:
    version: 2
    build-master:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - publish-latest:
                requires:
                    - build
                filters:
                    branches:
                        only: master
            - expresscart-deployment:
                requires:
                    - publish-latest
                filters:
                    branches:
                        only: master